### ISSUE TITLE
Split MIDI Range Voice stealing

### ISSUE THREAD

**Issue by mneme** [Befaco/MIDIThing2#10]
I have a midi keyboard connected.

### Voice 1:
**Note** 
- MIDI Range 24-127
- Assign: Low
- Priority: No Steal

**Gate**

### Voice 2:
**Note**:
- MIDI Range 0-23
- Assign: Low
- Priority: No Steal

**Gate**

Press and hold one key in range 24-127 -> Voice 1
Press an additional key in range 24-127 -> _Voice 2_

Press and hold key in range 0-23 -> Voice 2
Press an additional key in range 0-23 -> _No steal_

**Comment by xustafu** [comment]
Problem reproduced solved in current firmware!! 

We will be releasing a new testing firmware later today/tomorrow!!

**Comment by xustafu** [comment]
Fixed on 
https://github.com/Befaco/MIDIThing2/releases/tag/PreRelease_3_v1_1
Please test

**Comment by mneme** [comment]
@xustafu Hey, I'll roll the next regular release - don't quite have the time to test pre-releases as of now. :)
