### ISSUE TITLE
Allow free-running LFOs

### ISSUE THREAD

**Issue by TomFS** [Befaco/MIDIThing2#12]
Currently LFOs are tied to a voice, so they only cycle while a note is held on that voice.

It would be great to have free-running LFOs that can either:
- start when the unit boots and run at their programmed rate.
- start with midi transport commands and remain sync'd with the midi clock/tempo

**Comment by xustafu** [comment]
This is in our road map. There is a plan to implement a section of function generators.
This is scheduled to be worked on after the first wave of bug fixing. Thanks a lot for the suggestions!!

**Comment by xustafu** [comment]
Feature implemented in TEST firmware. Please  check!
https://github.com/Befaco/MIDIThing2/releases/tag/v1.2_TEST
