### ISSUE TITLE
Note voltage range is reset on voice updates

### ISSUE THREAD

**Issue by jrbellido** [Befaco/MIDIThing2#14]
Taking an empty setting:
1. We create a new voice V1 with Note only on port 01.
2. We adjust the note voltage range from 0/10v to -5/5v.
3. We add a gate to voice V1 on port 02.

The result is that now voice V1 has the Note voltage range at 0/10v again.

**Comment by xustafu** [comment]
Current code has this problem fixed. Later today we will tackle memory corruptio nissues and release a new testing firmware.
Thanks a lot for the patience and help on this one!

**Comment by jrbellido** [comment]
Yes, this bug is fixed in Pre3 1.1 (https://github.com/Befaco/MIDIThing2/issues/4#issuecomment-2138001171).

Thanks!
