### ISSUE TITLE
flip mode is not saved

### ISSUE THREAD

**Issue by bionoid** [Befaco/MIDIThing2#18]
The flip screen option is not saved in the memory when reload power

**Comment by xustafu** [comment]
Global features are not saved. This need to be addressed in future firmware updates. This is labelled as a known issue in experimental TEST Firmware 1.2

**Comment by bionoid** [comment]
This problem has been fixed
but in the test firmware other more critical ones appeared
separate topic

**Comment by xustafu** [comment]
> This problem has been fixed but in the test firmware other more critical ones appeared separate topic
Great to hear! Please do not hesitate to open new issues regarding these new ones you have spotted!
