### ISSUE TITLE
Feature request: Behaviour of notes as a slide depending on velocity

### ISSUE THREAD

**Issue by bionoid** [Befaco/MIDIThing2#19]
It would be useful to have the ability to disable the trigger (gate) if the note velocity value does not exceed a specified threshold (some low values, for example, 1-5). In this case, there will be a note slide (legato) and combined with slewlimiter, it will create the effect of the 303 sequencer.

**Comment by xustafu** [comment]
Unfortunately these changes are out of scope for now. I suggest to keep track of the repo and once code is available you can try to implement this yourself!
