### ISSUE TITLE
Feature Request: Noise(z) out

### ISSUE THREAD

**Issue by digitalies** [Befaco/MIDIThing2#20]
The manual says the oscillator introduces “digital dirt” in the higher frequencies. Would it hurt the outputs to have a constant source of noise? The Shuttle Cargo has some awesome noises ready to gate, filter, or dish out whatever.

If so, make it as dirty as possible!

**Comment by xustafu** [comment]
Labelled as feature request. Will investigate viability and come back with info to set expectations for this one

**Comment by xustafu** [comment]
Closing this issue as we will have a feature request thread for now.
https://github.com/Befaco/MIDIThing2/issues/46
