### ISSUE TITLE
Feature request: Arpeggiator

### ISSUE THREAD

**Issue by jrbellido** [Befaco/MIDIThing2#22]
It would be interesting to be able to receive one or more notes on a MIDI channel and, in sync with the MIDI clock, output the corresponding CV on the output port. Parameters such as scale, note length (or gate in additional port), direction, randomness, distance, triplets, octaves, etc. could be adjusted.

**Comment by xustafu** [comment]
Closing this issue as we will have a feature request thread for now.
https://github.com/Befaco/MIDIThing2/issues/46
