### ISSUE TITLE
Feature Request: Send MIDI start/stop message when internal MIDI clock starts/stops

### ISSUE THREAD

**Issue by markcrosbie** [Befaco/MIDIThing2#23]
In the TEST2 firmware the MIDI clock now lives on its own page which is great for setting up the clock.

But when the clock starts it does not send a MIDI start message, same for stopping the clock.

This would allow the MIDI Thing2 to be used as a MIDI clocking master in a modular setup with other MIDI controlled devices (like sequencers)

**Comment by xustafu** [comment]
Implemented in v1.2
