### ISSUE TITLE
Suggest creating a "Global Settings" menu that simplifies navigating through settings

### ISSUE THREAD

**Issue by markcrosbie** [Befaco/MIDIThing2#24]
In the 1.2 TEST2 firmware there are more global settings added. It takes a lot of knob turns to navigate through these as the MIDI Merge menu requires a lot of knob movements to get across it. Suggestion is to to gather all of these sub menus into a "Global Settings" (the name isn't important) menu that can be navigated using the knob and a menu item selected by pressing. This would improve usability

**Comment by xustafu** [comment]
Solved in TEST 3
