### ISSUE TITLE
Feature Request: Paraphonic Midi Gate Response

### ISSUE THREAD

**Issue by jjobse** [Befaco/MIDIThing2#27]
I would like to emulate the moog matriarch 4-voice architecture by assigning 4 voices midi notes. Each of the 4 voices also need a gate for the vca but for the filter they will need to share a singe gate output. As an added bonus I would like the same shared gate a second time for another vca after the filter. 

This could be achieved with an OR logic gate. So there could be a new logic function or a simplified “gate combiner” function.

**Comment by xustafu** [comment]
Closing this issue as we will have a feature request thread for now.
https://github.com/Befaco/MIDIThing2/issues/46
