### ISSUE TITLE
Feature Request: Toggle option to disable MIDI for ADSR

### ISSUE THREAD

**Issue by jjobse** [Befaco/MIDIThing2#28]
There are times when I want to set the ADSR up and then not have it change. When playing with other midi devices they may inadvertently modify the ADSR. 

EXAMPLE: Changing the octave range on the moog matriarchs oscillators will change the ADSR’s maximum amplitude.

**Comment by jjobse** [comment]
The ability to map ccs would also solve my issue. We could also have the option to map to null if we wanted no midi control.

**Comment by xustafu** [comment]
Closing as duplicated
