### ISSUE TITLE
Feature request: LFO Phase

### ISSUE THREAD

**Issue by jotel-california** [Befaco/MIDIThing2#31]
I have 2 features i think would be really neat. 

The first one would be, that the Lfos have a phase parameter, so the trigger doesnt always start them at the beginning of the wave, but anywhere from 0 to 360 degree. 

Another idea thats kinda related: have a mode where lfos are synced to the phase of the midi clock, instead of a trigger. This could work very well with the aforementioned phase parameter.

or, to avoid more menus: have them start in phase with the midi clock and the phase parameter by default (and after each stop command) and a received trigger overrides this. Best of both worlds.

**Comment by xustafu** [comment]
Closing this issue as we will have a feature request thread for now.
https://github.com/Befaco/MIDIThing2/issues/46
