### ISSUE TITLE
Add option for 1.2v/oct scaling

### ISSUE THREAD

**Issue by auxren** [Befaco/MIDIThing2#35]
Would it be possible to add either a per voice or a global option to select the scale besides v/oct?

**Comment by jotel-california** [comment]
look into the thread I opened about unprecice tracking, there is a test firmware where you can set the scaling. You should be able tochieve 1.2v tracking, at least between 2 and 8 V.

**Comment by xustafu** [comment]
Please check upcoming v1.2 to achieve this
