### ISSUE TITLE
feature request: cc over int clock

### ISSUE THREAD

**Issue by besb1n** [Befaco/MIDIThing2#36]
control over the internal clocks tempo via cc. also control over start/stop via cc. for example, the 8mu controller doesnt send clock messages, but if you made the midithings int clock controllable via cc, you could assign tempo to a slider and start/stop to one of the buttons on the 8mu.

**Comment by xustafu** [comment]
Closing this issue as we will have a feature request thread for now.
https://github.com/Befaco/MIDIThing2/issues/46
