### ISSUE TITLE
Clocks from multiple sources being summed + Host 2-4 not sending clock

### ISSUE THREAD

**Issue by xustafu** [Befaco/MIDIThing2#37]
When you have midi clock coming in from the midi in and and the usb host, the bpm is added together instead of one taking priority. Meaning if my midi in runs at 120 and the Usb Host at 80bpm, the midi thing will run at 200bpm. Also I was not able to send out midi clock via the usb host ports 2-4. No matter what I check/uncheck, it does not output clock data.

**Comment by xustafu** [comment]
NEW EDIT: All Note Off implemented

Please check this firmware. Start stop message is sent but ~~all note off mesage is in process. Can you check with a midi monitor that all note off message is sent before or after the stop?~~
USB hosts is still untested!
[MidiThing2_1_2_TEST_3_FIX.zip](https://github.com/user-attachments/files/17450057/MidiThing2_1_2_TEST_3_FIX.zip)

**Comment by xustafu** [comment]
Solved in v1.2 TEST3
https://github.com/Befaco/MIDIThing2/releases/tag/v1.2_TEST3

**Comment by modularev** [comment]
not sure if I overlooked another open issue but on v1.2_TEST3 the Clocks from multiple sources are still being summed? You could either change the menu for the channel selection in the clock related menu for USB + MIDI / USB / MIDI or maybe just change the clock selector between INTERNAL / MIDI / USB?

Is there a timeline when you'll release the sourcecode? happy to take look at it...

**Comment by xustafu** [comment]
> not sure if I overlooked another open issue but on v1.2_TEST3 the Clocks from multiple sources are still being summed? You could either change the menu for the channel selection in the clock related menu for USB + MIDI / USB / MIDI or maybe just change the clock selector between INTERNAL / MIDI / USB?
> 
> Is there a timeline when you'll release the sourcecode? happy to take look at it...

From Test3 we have changed the functionality of clock column in the midi routing screen.
Now the clk colum enables or disables clock handling per source. So to avoid weird clocking issues, disable all clock sources except the one you want to use.

**Comment by xustafu** [comment]
@modularev during the afternoon I will send you an invite for our internal repo.
We hope to release the code after official v1.2 firmwqare release, but will be nice to have fresh eyes over it before that :)

**Comment by xustafu** [comment]
@modularev sent you an invite,.Most issues are in spanish, sorry. Also keep in mind that code is barely commented and still in need of clean-up!
Ask @SergioRetamero any question you might have or open issues over there!
