### ISSUE TITLE
Hanging Gates 

### ISSUE THREAD

**Issue by jotel-california** [Befaco/MIDIThing2#38]
When you stop any playing midi sequence while a note is being held, the gate out stays high. It would be great, if the Midi Stop Command would set all gates low. Maybe implemented that this can be changed in the settings.

**Comment by xustafu** [comment]
Can you try this code?
[MidiThing2_TEST3_All_note_off.zip](https://github.com/user-attachments/files/17458965/MidiThing2_TEST3_All_note_off.zip)

Thanks a lot for the feedback and the patience :)

**Comment by jotel-california** [comment]
Perfect, that fixed the problem. Hanging notes are now gone. 


No Problem. I rather have a few bugs and the company cares about the project, rather than a „finished“ product that gets abandoned after launch.

If I have time I help. 



Jo
