### ISSUE TITLE
Feature request: proper synced LFO multipliers/dividers (impossible to have dotted notes)

### ISSUE THREAD

**Issue by jotel-california** [Befaco/MIDIThing2#41]
Right now, the multipliers in the LFO rate section are kind of limiting and unintuitive.
When I see 1/16th x3 what I would expect to get is a dotted 8th. But what you get is a third of the time of a sixteenth. 
(one triolic 16th) This means, dotted values are impossible to obtain

In the current Firmware, all you have is even times (whole, half, quarter, 8th, 16th and so on, not counting the 1/24th) and the multiplier is actually a divider of the time. To obtain a dotted rhythm, lets say a dotted 8th for this example, you would need 3 16ths. But there is now way to obtain that. If I use a whole note, so 16 16ths, there is no whole number that I can divide this with so you get 3 in the end. The same is true for 4 (quarter), 8 (half), 32 (double), etc. 

The suggestion would be to extend the scale to dividers, meaning if you go lower than x1 you get /2, /3, /4 etc.
With the divisors shortening the time (like the multipliers are doing now) and the multipliers slowing the time. 
in my opininion x15 up to /15 down would be enough, to not extend the range too far. 

This would make sense, because if you multiply a time, the duration gets longer. Also it would be much more easy to set dotted or triolic speeds, because right now you have to use bigger measures multiplied by odd numbers, and I'm not even sure you can get reliable dotted values.

**Comment by jotel-california** [comment]
feel free to contact me again with a test firmware.

**Comment by xustafu** [comment]
Closing this issue as we will have a feature request thread for now.
https://github.com/Befaco/MIDIThing2/issues/46
