### ISSUE TITLE
Feature request: reorder voltage ranges

### ISSUE THREAD

**Issue by jotel-california** [Befaco/MIDIThing2#44]
This is just a small thing, nothing critical.
Right now the voltage ranges are ordered this way: 0-10V, -5/+5V, 0-8V, 0-5V.
In my opinion it would make more sense to order them to: -5/+5V, 0-10V, 0-8V, 0-5V. 
Alternatively: 0-10V, 0-8V, 0-5V, -5/+5V

This way it's more intuitive, because now when you want to go from 0-10 to 0-8 you have to the negative first.

**Comment by xustafu** [comment]
Closing this issue as we will have a feature request thread for now.
https://github.com/Befaco/MIDIThing2/issues/46
