### ISSUE TITLE
Note Priority: "Last" not working properly

### ISSUE THREAD

**Issue by WulliMV** [Befaco/MIDIThing2#8]
Note priority only works with 2 pressed keys. If more than 2 keys are pressed, it reverts to the first pressed note.

**Comment by xustafu** [comment]
Tested with pre-def 1, sending 4 notes that are assigned to each channel. Working correctly.
Pleaseprovide precise stepstoreplicate your issue.
According to user manual, module is working as described. "Last" will give priority to the last note receives, meaning the  new note will steal the oldest note.

**Comment by WulliMV** [comment]
Works now flawlessly - memory reset helped...

**Comment by xustafu** [comment]
Nice bit of information! might be useful to know that memory corruption might go this deep. 
Will keep up trying to replicate!!!

**Comment by WulliMV** [comment]
oh, still something: if I press keys, e.g. four in a row and start to release again one after the other, it jumps back to the first instead of the last. here it is again ;-D

**Comment by xustafu** [comment]
I load Pre def-1. Priority is selected to last.
Pressing four keys in a MIDI keyboard, having the four voices selected. Then I release one by one. It acts normally.
Cannot replicate. Please elaborate steps to get the error

**Comment by WulliMV** [comment]
ok I see. the issue I describe is in monophonic mode, so only one voice with "last" set as priority. then the behaviour i'd expect after releasing the fourth key again that it goes back to the third, not the first note
