### ISSUE TITLE
Monophonic Note Priority

### ISSUE THREAD

**Issue by WulliMV** [Befaco/MIDIThing2#9]
ok I see. the issue I describe is in monophonic mode, so only one voice with "last" set as priority. then the behaviour i'd expect after releasing the fourth key again that it goes back to the third, not the first note

_Originally posted by @WulliMV in https://github.com/Befaco/MIDIThing2/issues/8#issuecomment-2104108452_
![Priority](https://user-images.githubusercontent.com/169186429/329761335-7bebb006-a28f-4622-90b9-66f3075a3335.jpg)

            
I put a midi track together to illustrate.. In this keyorder I'd expect the blue path, but currently the red path happens.. IF I am in a patch where I only have one voice, monophonic, proirity set to "last". See attachments in the comment below, also my *.json of the patch.

**Comment by WulliMV** [comment]
![Priority](https://github.com/Befaco/MIDIThing2/assets/169186429/068603a5-e7fc-42f9-bf9e-7ee0e4a5e57f)
[MTConfig2024_May_9_17_44_21.json](https://github.com/Befaco/MIDIThing2/files/15281934/MTConfig2024_May_9_17_44_21.json)

**Comment by xustafu** [comment]
WE have duplictaed this. Seems that algorythm only applies to "stealing" of notes, we need to implement the algorythm to "recovering" notes.

So setting this to feature request and we will work on it!!
